[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cadaver = { path = "../cadaver" }
macroquad = { version = "0.4.8", default-features = false, features = [] }