[package]
name = "cadaver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap = "1.0.7"
geom = { workspace = true }

lazy_static = "1.4.0"